### DISCUSSION TITLE
What custom css do I add to make the text input box shorter. I want to make it the same with as the message area

### DISCUSSION THREAD

**Discussion by alkapwn3d** [pnd280/complexity#43] [General]
right now the text input box is too wide in my opinion. i want to make it the same side are the area that gets populated but the response

**Comment by pnd280** [comment]
I apologize for the late reply, here is the css code:
```css
.pointer-events-none.fixed.bottom-mobileNavHeight.z-10 .pointer-events-auto.md\:col-span-8:has(textarea) {
  grid-column: span 8 / span 8 !important;
}
```

custom theme will be improved in future versions with less hard-coded styles
